### PR TITLE
finished all Fedora's Flavors

### LINKED ISSUE #5: [Fedora] Distribution History
- Release date.
  - Flavors. (if exist)
  - Based on distribution. (if exist) (example: Pop!_OS is based on Debian)

### PR DESCRIPTION
**Pull request by KenzyAdel**

### CODE REVIEW

**Review by thisisamna — CHANGES_REQUESTED** [review]
Really great work! Just fix the space in the title so that it renders properly.

**Comment by KenzyAdel** [comment]
Spaces are done

**Comment by thisisamna** [comment]
Hmm the changes aren't here yet. Have you committed and pushed?

**Comment by KenzyAdel** [comment]
Sorry for forgetting to push my changes

**Comment by thisisamna** [comment]
No worries Kenzy, thank you for your hard work! Reviewing right now

**Review by thisisamna — APPROVED** [review]
Awesome!

**Pull request merged**
